/**
 * Concat - concatenates files.
 *
 * Actual config is generated by usemin task.
 */
module.exports = function(grunt) {
  'use strict';

  grunt.config('concat', {});

  grunt.loadNpmTasks('grunt-contrib-concat');
};
